spring.application.name=passkey-demo
spring.main.banner-mode=off
server.port=5000

# SQLite DataSource
spring.datasource.url=jdbc:sqlite:passkey-demo.db?journal_mode=WAL
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
